spring:
  application:
    name: GreenGramVer1
  datasource:
    url: jdbc:mariadb://localhost/greengram_ver1
    username: root
    password: green502

mybatis:
  mapper-locations: xml/**/*.xml

springdoc:
  swagger-ui:
    default-model-expand-depth: 2
    default-models-expand-depth: -1
    operations-sorter: method
    path: /swagger